# language
language: node_js
node_js: 12.16.3
cache: npm

branches:
    only:
    - master

# installation
install: 
    npm install

# tasks
scripts: 
    - npm run lint
    

deploy:
    provider: script
    script: 
        - npm run buildDocker
    script:
        - npm run dockerLogin
    script:
        - npm run dockerTag
    script:
        - npm run dockerPush
    # on:
    #     branch: master