# CONFIGURATION

# specify programming language
language: node_js
node_js: 12.16.3
cache: npm

# installation phase
install:
  - npm install

# run tasks
jobs:
  include:
    - name: Run lint
      script: npm run lint

    - name: Build Docker image
      script: npm run buildDocker

    - name: Push to Docker Hub
      if: (type = push AND branch = master)
      script: npm run dockerLogin && npm run dockerTag && npm run dockerPush