# CONFIGURATION

# specify programming language
language: node_js
node_js: 12.16.3
cache: npm
    
# run tasks
jobs:
  include:
    - stage: compile
      script: npm install

    - stage: lint
      script: npm run lint

    - stage: test
      script: npm run test

    - stage: deploy
      if: (type = push AND branch = master)
      # - name: Push to Docker Hub
      # if: (type = push AND branch = master)
      script: npm run dockerLogin && npm run buildDocker && npm run dockerTag && npm run dockerPush
