# CONFIGURATION

# specify programming language
language: node_js
node_js: 12.16.3
cache: npm

# installation phase
install:
  - npm install

# tasks phase
script:
  - npm run lint
  - npm run buildDocker
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run pushToDockerHub; fi
  
