# CONFIGURATION

# specify programming language
language: node_js
node_js: 10.15.0
cache: npm

# installation phase
install:
  - npm i

# tasks phase
script:
  - npm run lint
  - npm run buildDocker
  - if [ "$TRAVIS_BRANCH" = "master" | "TRAVIS_PULL_REQUEST" = "false" ]; then npm run dockerLogin; fi
  - if [ "$TRAVIS_BRANCH" = "master" | "TRAVIS_PULL_REQUEST" = "false" ]; then 
  npm run dockerTag && npm run dockerPush; fi
