# CONFIGURATION

# specify programming language
language: node_js
node_js: 12.16.3
cache: npm

branches:
  only: 
    - master
    
# installation phase
install:
  - npm install

# before_script:
#   - 

# run tasks
jobs:
  include:
    - stage: test
      # - name: Run lint
      script: npm run lint

    # - name: Build Docker image
    # - script: npm run buildDocker
    - stage: deploy
      # - name: Push to Docker Hub
      # if: (type = push AND branch = master)
      script: npm run dockerLogin && npm run buildDocker && npm run dockerTag && npm run dockerPush
