# CONFIGURATION

# specify programming language
language: node_js
node_js: 12.16.3
cache: npm

branches:
  only: 
    - master

services:
  - docker

# installation phase
install:
  - npm install


# run tasks
jobs:
  include:
    - name: Run lint
      script: npm run lint

    - name: Build Docker image
      script: docker build -t localhost:32000/node-web-app:latest . --no-cache

    # - name: Tag Docker Image
      # if: (type = push AND branch = master)
      script: docker tag localhost:32000/node-web-app iivashchuk/node-web-app:latest
      script: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    # - name: Push to Docker Hub
      # if: (type = push AND branch = master)
      script: docker push $DOCKER_USERNAME/node-web-app:latest