# CONFIGURATION

# specify programming language
# language: node_js
# node_js: 12.16.3
# cache: npm

# # installation phase
# install:
#   - npm install

# # tasks phase
# script:
#   - npm run lint
#   - npm run buildDocker
  
# deploy:
#   provider: script
#   script: 
#       - npm run pushToDockerHub
#   on:
#       branch: master



language: node_js
node_js: 12.16.3
cache: npm

jobs:
  include:
    - name: Run lint
      script: yarn lint

    - name: Build Docker image
      script: yarn buildDocker

    - name: push to Docker Hub
      if: (type = push AND branch = master)
      script: yarn dockerLogin && yarn dockerTag && yarn dockerPush